package scheduleimport_test

import (
	"context"
	"strings"
	"testing"
	"time"

	"nfc-time-tracking-server/internal/model"
	"nfc-time-tracking-server/internal/service/scheduleimport"
	"nfc-time-tracking-server/internal/store/sqlite"
)

func TestApply_WritesScheduleAndSkipsHolidayColumn(t *testing.T) {
	db, err := sqlite.Open(":memory:")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	ctx := context.Background()

	us := sqlite.NewUserStore(db)
	u := &model.User{
		Username: "a", PasswordHash: "x", DisplayName: "Anna Tester",
		Role: model.RoleUser, Active: true,
	}
	if err := us.Create(ctx, u); err != nil {
		t.Fatal(err)
	}

	hs := sqlite.NewHolidayStore(db)
	mon := time.Date(2026, 3, 16, 12, 0, 0, 0, time.Local)
	tue := mon.AddDate(0, 0, 1)
	if err := hs.Create(ctx, &model.Holiday{HolidayDate: tue.Format("2006-01-02"), Name: "Testfeiertag", AutoGenerated: false}); err != nil {
		t.Fatal(err)
	}

	dates := [5]string{
		mon.Format("2006-01-02"),
		tue.Format("2006-01-02"),
		mon.AddDate(0, 0, 2).Format("2006-01-02"),
		mon.AddDate(0, 0, 3).Format("2006-01-02"),
		mon.AddDate(0, 0, 4).Format("2006-01-02"),
	}
	isoY, isoW := mon.ISOWeek()

	parsed := &scheduleimport.ParsedSheet{
		Weeks: []scheduleimport.ParsedWeek{{
			ISOYear: isoY,
			ISOWk:   isoW,
			Notes:   "<p>Hinweis</p>",
			Dates:   dates,
			Rows: []scheduleimport.ParsedEmployeeRow{{
				RawName: "Anna Tester",
				Cells:   [5]string{"9:00-17:00", "soll übersprungen", "9:00-17:00", "", ""},
			}},
		}},
	}

	ss := sqlite.NewScheduleStore(db)
	as := sqlite.NewAbsenceStore(db)
	deps := scheduleimport.Deps{
		Users: us, Schedules: ss, Absences: as, Holidays: hs, Closures: sqlite.NewClosureDayStore(db),
		Claims: sqlite.NewCompensationDayClaimStore(db), TeamMeetings: nil,
	}

	const importDay = "2026-01-01"
	rep, err := scheduleimport.Apply(ctx, deps, parsed, 1, importDay)
	if err != nil {
		t.Fatal(err)
	}
	if rep.WeekNotesUpdated != 1 {
		t.Fatalf("week notes: %+v", rep)
	}

	sMon, err := ss.GetForUserDate(ctx, u.ID, dates[0])
	if err != nil || sMon == nil || sMon.ShiftStart != "09:00" {
		t.Fatalf("Mo schedule: %+v err=%v", sMon, err)
	}
	sTue, err := ss.GetForUserDate(ctx, u.ID, dates[1])
	if err != nil || sTue != nil {
		t.Fatalf("Di (Feiertag) sollte keine Schicht haben: %+v", sTue)
	}
	sWed, err := ss.GetForUserDate(ctx, u.ID, dates[2])
	if err != nil || sWed == nil {
		t.Fatalf("Mi schedule: %+v err=%v", sWed, err)
	}
	if rep.AbsencesSkipped == 0 {
		t.Fatal("expected skipped cells for holiday column")
	}
}

func TestApply_IdempotentVacation_NoDuplicateReplaceCounts(t *testing.T) {
	db, err := sqlite.Open(":memory:")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	ctx := context.Background()

	us := sqlite.NewUserStore(db)
	u := &model.User{
		Username: "b", PasswordHash: "x", DisplayName: "Bob Urlaub",
		Role: model.RoleUser, Active: true,
	}
	if err := us.Create(ctx, u); err != nil {
		t.Fatal(err)
	}

	hs := sqlite.NewHolidayStore(db)
	mon := time.Date(2026, 4, 13, 12, 0, 0, 0, time.Local)
	dates := [5]string{
		mon.Format("2006-01-02"),
		mon.AddDate(0, 0, 1).Format("2006-01-02"),
		mon.AddDate(0, 0, 2).Format("2006-01-02"),
		mon.AddDate(0, 0, 3).Format("2006-01-02"),
		mon.AddDate(0, 0, 4).Format("2006-01-02"),
	}
	isoY, isoW := mon.ISOWeek()

	parsed := &scheduleimport.ParsedSheet{
		Weeks: []scheduleimport.ParsedWeek{{
			ISOYear: isoY,
			ISOWk:   isoW,
			Dates:   dates,
			Rows: []scheduleimport.ParsedEmployeeRow{{
				RawName: "Bob Urlaub",
				Cells:   [5]string{"U", "", "", "", ""},
			}},
		}},
	}

	ss := sqlite.NewScheduleStore(db)
	as := sqlite.NewAbsenceStore(db)
	deps := scheduleimport.Deps{
		Users: us, Schedules: ss, Absences: as, Holidays: hs, Closures: sqlite.NewClosureDayStore(db),
		Claims: sqlite.NewCompensationDayClaimStore(db), TeamMeetings: nil,
	}

	const importDay = "2026-01-01"
	rep1, err := scheduleimport.Apply(ctx, deps, parsed, 1, importDay)
	if err != nil {
		t.Fatal(err)
	}
	if rep1.AbsencesCreated != 1 || rep1.AbsencesReplaced != 0 {
		t.Fatalf("first import: created=%d replaced=%d want 1/0", rep1.AbsencesCreated, rep1.AbsencesReplaced)
	}

	rep2, err := scheduleimport.Apply(ctx, deps, parsed, 1, importDay)
	if err != nil {
		t.Fatal(err)
	}
	if rep2.AbsencesCreated != 0 || rep2.AbsencesReplaced != 0 {
		t.Fatalf("second import same sheet: created=%d replaced=%d want 0/0", rep2.AbsencesCreated, rep2.AbsencesReplaced)
	}

	got, err := as.GetForUserDate(ctx, u.ID, dates[0])
	if err != nil || got == nil || got.AbsenceType != model.AbsenceVacation {
		t.Fatalf("absence: %+v err=%v", got, err)
	}
}

func TestApply_SkippedHolidayCountsWorkdaysNotPerEmployeeCells(t *testing.T) {
	db, err := sqlite.Open(":memory:")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	ctx := context.Background()

	us := sqlite.NewUserStore(db)
	for _, u := range []*model.User{
		{Username: "a1", PasswordHash: "x", DisplayName: "Anna Tester", Role: model.RoleUser, Active: true},
		{Username: "b1", PasswordHash: "x", DisplayName: "Bob Tester", Role: model.RoleUser, Active: true},
	} {
		if err := us.Create(ctx, u); err != nil {
			t.Fatal(err)
		}
	}

	mon := time.Date(2026, 5, 4, 12, 0, 0, 0, time.Local)
	dates := [5]string{
		mon.Format("2006-01-02"),
		mon.AddDate(0, 0, 1).Format("2006-01-02"),
		mon.AddDate(0, 0, 2).Format("2006-01-02"),
		mon.AddDate(0, 0, 3).Format("2006-01-02"),
		mon.AddDate(0, 0, 4).Format("2006-01-02"),
	}
	isoY, isoW := mon.ISOWeek()

	parsed := &scheduleimport.ParsedSheet{
		Weeks: []scheduleimport.ParsedWeek{{
			ISOYear: isoY,
			ISOWk:   isoW,
			Dates:   dates,
			// Di, Mi, Do als Feiertagsspalten — zwei Mitarbeiter mit Inhalt: Zählung = 3 Tage, nicht 6 Zellen.
			SkipDay: [5]bool{false, true, true, true, false},
			Rows: []scheduleimport.ParsedEmployeeRow{
				{
					RawName: "Anna Tester",
					Cells:   [5]string{"09:00-17:00", "x", "x", "x", "09:00-17:00"},
				},
				{
					RawName: "Bob Tester",
					Cells:   [5]string{"09:00-17:00", "x", "x", "x", "09:00-17:00"},
				},
			},
		}},
	}

	ss := sqlite.NewScheduleStore(db)
	as := sqlite.NewAbsenceStore(db)
	deps := scheduleimport.Deps{
		Users: us, Schedules: ss, Absences: as, Holidays: sqlite.NewHolidayStore(db),
		Closures: sqlite.NewClosureDayStore(db), Claims: sqlite.NewCompensationDayClaimStore(db),
		TeamMeetings: nil,
	}

	const importDay = "2026-01-01"
	rep, err := scheduleimport.Apply(ctx, deps, parsed, 1, importDay)
	if err != nil {
		t.Fatal(err)
	}
	if rep.AbsencesSkipped != 3 {
		t.Fatalf("AbsencesSkipped: got %d want 3 (drei Feiertagstage, nicht 6 Mitarbeiterzellen)", rep.AbsencesSkipped)
	}
}

func TestApply_DoesNotMutatePastDates(t *testing.T) {
	db, err := sqlite.Open(":memory:")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	ctx := context.Background()

	us := sqlite.NewUserStore(db)
	u := &model.User{
		Username: "p", PasswordHash: "x", DisplayName: "Past User",
		Role: model.RoleUser, Active: true,
	}
	if err := us.Create(ctx, u); err != nil {
		t.Fatal(err)
	}

	mon := time.Date(2026, 3, 16, 12, 0, 0, 0, time.Local)
	dates := [5]string{
		mon.Format("2006-01-02"),
		mon.AddDate(0, 0, 1).Format("2006-01-02"),
		mon.AddDate(0, 0, 2).Format("2006-01-02"),
		mon.AddDate(0, 0, 3).Format("2006-01-02"),
		mon.AddDate(0, 0, 4).Format("2006-01-02"),
	}
	isoY, isoW := mon.ISOWeek()

	ss := sqlite.NewScheduleStore(db)
	if err := ss.Set(ctx, &model.Schedule{
		UserID: u.ID, ScheduleDate: dates[0],
		ShiftStart: "09:00", ShiftEnd: "17:00",
	}); err != nil {
		t.Fatal(err)
	}

	parsed := &scheduleimport.ParsedSheet{
		Weeks: []scheduleimport.ParsedWeek{{
			ISOYear: isoY,
			ISOWk:   isoW,
			Notes:   "<p>Alte Woche</p>",
			Dates:   dates,
			Rows: []scheduleimport.ParsedEmployeeRow{{
				RawName: "Past User",
				Cells:   [5]string{"10:00-18:00", "U", "F", "09:00-17:00", ""},
			}},
		}},
	}

	as := sqlite.NewAbsenceStore(db)
	deps := scheduleimport.Deps{
		Users: us, Schedules: ss, Absences: as, Holidays: sqlite.NewHolidayStore(db),
		Closures: sqlite.NewClosureDayStore(db), Claims: sqlite.NewCompensationDayClaimStore(db),
		TeamMeetings: nil,
	}

	const todayPastImport = "2026-06-15"
	rep, err := scheduleimport.Apply(ctx, deps, parsed, 1, todayPastImport)
	if err != nil {
		t.Fatal(err)
	}
	if rep.PastCellsSkipped != 4 {
		t.Fatalf("PastCellsSkipped: got %d want 4 (Mo–Do mit Inhalt)", rep.PastCellsSkipped)
	}
	if rep.WeekNotesUpdated != 0 || rep.PastWeekNotesSkipped != 1 {
		t.Fatalf("week notes: updated=%d pastSkipped=%d", rep.WeekNotesUpdated, rep.PastWeekNotesSkipped)
	}
	if rep.SchedulesWritten != 0 || rep.SchedulesDeleted != 0 {
		t.Fatalf("no schedule mutations: written=%d deleted=%d", rep.SchedulesWritten, rep.SchedulesDeleted)
	}
	if rep.AbsencesCreated != 0 {
		t.Fatalf("absences created: %d", rep.AbsencesCreated)
	}

	sMon, err := ss.GetForUserDate(ctx, u.ID, dates[0])
	if err != nil || sMon == nil || sMon.ShiftStart != "09:00" || sMon.ShiftEnd != "17:00" {
		t.Fatalf("Mo Schicht unverändert: %+v err=%v", sMon, err)
	}
}

func TestApply_TeamMeetingsKTFromParsedWeek(t *testing.T) {
	db, err := sqlite.Open(":memory:")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	ctx := context.Background()

	us := sqlite.NewUserStore(db)
	u1 := &model.User{
		Username: "a1", PasswordHash: "x", DisplayName: "Anna Tester",
		Role: model.RoleUser, Active: true,
	}
	u2 := &model.User{
		Username: "b1", PasswordHash: "x", DisplayName: "Bob Tester",
		Role: model.RoleUser, Active: true,
	}
	if err := us.Create(ctx, u1); err != nil {
		t.Fatal(err)
	}
	if err := us.Create(ctx, u2); err != nil {
		t.Fatal(err)
	}
	u2.DefaultTeamMeetingParticipant = false
	if err := us.Update(ctx, u2); err != nil {
		t.Fatal(err)
	}

	mon := time.Date(2026, 3, 16, 12, 0, 0, 0, time.Local)
	isoY, isoW := mon.ISOWeek()
	dates := [5]string{
		mon.Format("2006-01-02"),
		mon.AddDate(0, 0, 1).Format("2006-01-02"),
		mon.AddDate(0, 0, 2).Format("2006-01-02"),
		mon.AddDate(0, 0, 3).Format("2006-01-02"),
		mon.AddDate(0, 0, 4).Format("2006-01-02"),
	}

	secLine := scheduleimport.ParsedTeamMeetingLine{
		Kind:    scheduleimport.TeamMeetingLineScheduled,
		KTStart: "10:00",
		KTEnd:   "11:00",
	}

	parsed := &scheduleimport.ParsedSheet{
		Weeks: []scheduleimport.ParsedWeek{{
			ISOYear: isoY,
			ISOWk:   isoW,
			Dates:   dates,
			Rows: []scheduleimport.ParsedEmployeeRow{
				{RawName: "Anna Tester", Cells: [5]string{"9:00-17:00", "", "", "", ""}},
				{RawName: "Bob Tester", Cells: [5]string{"9:00-17:00", "", "", "", ""}},
			},
			TeamMondaySections: []scheduleimport.ParsedTeamMondaySection{
				{Line: secLine, EmployeeRawNames: []string{"Anna Tester", "Bob Tester"}},
			},
		}},
	}

	ss := sqlite.NewScheduleStore(db)
	tms := sqlite.NewTeamMeetingStore(db)
	deps := scheduleimport.Deps{
		Users: us, Schedules: ss, Absences: sqlite.NewAbsenceStore(db),
		Holidays: sqlite.NewHolidayStore(db), Closures: sqlite.NewClosureDayStore(db),
		Claims: sqlite.NewCompensationDayClaimStore(db), TeamMeetings: tms,
	}

	rep, err := scheduleimport.Apply(ctx, deps, parsed, 1, "2026-01-01")
	if err != nil {
		t.Fatal(err)
	}
	if rep.TeamMeetingsCreated != 1 {
		t.Fatalf("team meetings created: %d", rep.TeamMeetingsCreated)
	}

	list, err := tms.ListByWeek(ctx, isoY, isoW)
	if err != nil {
		t.Fatal(err)
	}
	if len(list) != 1 {
		t.Fatalf("meetings in db: %d", len(list))
	}
	if list[0].Kind != model.TeamMeetingKindKT {
		t.Fatalf("kind: %s", list[0].Kind)
	}
	if len(list[0].UserIDs) != 1 {
		t.Fatalf("user ids: %v", list[0].UserIDs)
	}
	if list[0].UserIDs[0] != u1.ID {
		t.Fatalf("expected only Anna (id %d), got %v", u1.ID, list[0].UserIDs)
	}
}

func TestApply_WarnsShiftOnFixedFreeWeekday(t *testing.T) {
	db, err := sqlite.Open(":memory:")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	ctx := context.Background()

	us := sqlite.NewUserStore(db)
	u := &model.User{
		Username: "fri", PasswordHash: "x", DisplayName: "Freitag Frei",
		Role: model.RoleUser, Active: true,
		FixedNonWorkWeekdays: []int{int(time.Friday)},
	}
	if err := us.Create(ctx, u); err != nil {
		t.Fatal(err)
	}

	mon := time.Date(2026, 3, 16, 12, 0, 0, 0, time.Local)
	fri := mon.AddDate(0, 0, 4)
	dates := [5]string{
		mon.Format("2006-01-02"),
		mon.AddDate(0, 0, 1).Format("2006-01-02"),
		mon.AddDate(0, 0, 2).Format("2006-01-02"),
		mon.AddDate(0, 0, 3).Format("2006-01-02"),
		fri.Format("2006-01-02"),
	}
	isoY, isoW := mon.ISOWeek()

	parsed := &scheduleimport.ParsedSheet{
		Weeks: []scheduleimport.ParsedWeek{{
			ISOYear: isoY,
			ISOWk:   isoW,
			Dates:   dates,
			Rows: []scheduleimport.ParsedEmployeeRow{{
				RawName: "Freitag Frei",
				Cells:   [5]string{"", "", "", "", "9:00-17:00"},
			}},
		}},
	}

	ss := sqlite.NewScheduleStore(db)
	deps := scheduleimport.Deps{
		Users: us, Schedules: ss, Absences: sqlite.NewAbsenceStore(db),
		Holidays: sqlite.NewHolidayStore(db), Closures: sqlite.NewClosureDayStore(db),
		Claims: sqlite.NewCompensationDayClaimStore(db), TeamMeetings: nil,
	}

	const importDay = "2026-01-01"
	rep, err := scheduleimport.Apply(ctx, deps, parsed, 1, importDay)
	if err != nil {
		t.Fatal(err)
	}
	if rep.SchedulesWritten != 1 {
		t.Fatalf("SchedulesWritten: got %d want 1", rep.SchedulesWritten)
	}

	sFri, err := ss.GetForUserDate(ctx, u.ID, dates[4])
	if err != nil || sFri == nil || sFri.ShiftStart != "09:00" {
		t.Fatalf("Fr schedule: %+v err=%v", sFri, err)
	}

	var fixedFreeWarns []string
	for _, w := range rep.Warnings {
		if strings.Contains(w, "festem freien Tag") {
			fixedFreeWarns = append(fixedFreeWarns, w)
		}
	}
	if len(fixedFreeWarns) != 1 {
		t.Fatalf("fixed-free warnings: got %d want 1: %v", len(fixedFreeWarns), rep.Warnings)
	}
	if !strings.Contains(fixedFreeWarns[0], "Freitag Frei") || !strings.Contains(fixedFreeWarns[0], "Freitag") {
		t.Fatalf("warning text: %q", fixedFreeWarns[0])
	}
}

func TestApply_NoWarnShiftOnNormalWorkday(t *testing.T) {
	db, err := sqlite.Open(":memory:")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	ctx := context.Background()

	us := sqlite.NewUserStore(db)
	u := &model.User{
		Username: "norm", PasswordHash: "x", DisplayName: "Normal Tag",
		Role: model.RoleUser, Active: true,
		FixedNonWorkWeekdays: []int{int(time.Friday)},
	}
	if err := us.Create(ctx, u); err != nil {
		t.Fatal(err)
	}

	mon := time.Date(2026, 3, 16, 12, 0, 0, 0, time.Local)
	dates := [5]string{
		mon.Format("2006-01-02"),
		mon.AddDate(0, 0, 1).Format("2006-01-02"),
		mon.AddDate(0, 0, 2).Format("2006-01-02"),
		mon.AddDate(0, 0, 3).Format("2006-01-02"),
		mon.AddDate(0, 0, 4).Format("2006-01-02"),
	}
	isoY, isoW := mon.ISOWeek()

	parsed := &scheduleimport.ParsedSheet{
		Weeks: []scheduleimport.ParsedWeek{{
			ISOYear: isoY,
			ISOWk:   isoW,
			Dates:   dates,
			Rows: []scheduleimport.ParsedEmployeeRow{{
				RawName: "Normal Tag",
				Cells:   [5]string{"9:00-17:00", "", "", "", ""},
			}},
		}},
	}

	ss := sqlite.NewScheduleStore(db)
	deps := scheduleimport.Deps{
		Users: us, Schedules: ss, Absences: sqlite.NewAbsenceStore(db),
		Holidays: sqlite.NewHolidayStore(db), Closures: sqlite.NewClosureDayStore(db),
		Claims: sqlite.NewCompensationDayClaimStore(db), TeamMeetings: nil,
	}

	rep, err := scheduleimport.Apply(ctx, deps, parsed, 1, "2026-01-01")
	if err != nil {
		t.Fatal(err)
	}
	for _, w := range rep.Warnings {
		if strings.Contains(w, "festem freien Tag") {
			t.Fatalf("unexpected fixed-free warning: %q", w)
		}
	}
}
