package model

const (
	HolidayKindFeiertag  = "feiertag"
	HolidayKindBrauchtum = "brauchtum"
)

type Holiday struct {
	ID            int    `json:"id"`
	HolidayDate   string `json:"holiday_date"`
	Name          string `json:"name"`
	Kind          string `json:"kind"`
	AutoGenerated bool   `json:"auto_generated"`
}

type ClosureDay struct {
	ID          int    `json:"id"`
	ClosureDate string `json:"closure_date"`
	Name        string `json:"name"`
	CreatedBy   int    `json:"created_by"`
}
