package holidaysync

import (
	"context"
	"testing"
	"time"

	"nfc-time-tracking-server/internal/model"
	"nfc-time-tracking-server/internal/service/timecalc"
	"nfc-time-tracking-server/internal/store/sqlite"
)

func TestEnsureNRWHolidays_idempotent(t *testing.T) {
	db, err := sqlite.Open(":memory:")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	ctx := context.Background()
	hs := sqlite.NewHolidayStore(db)
	year := 2026
	wantN := len(timecalc.GenerateNRWHolidays(year))

	if err := EnsureNRWHolidays(ctx, hs, []int{year}); err != nil {
		t.Fatal(err)
	}
	list, err := hs.ListByYear(ctx, year)
	if err != nil {
		t.Fatal(err)
	}
	if len(list) != wantN {
		t.Fatalf("after first ensure: got %d holidays, want %d", len(list), wantN)
	}

	if err := EnsureNRWHolidays(ctx, hs, []int{year}); err != nil {
		t.Fatal(err)
	}
	list2, err := hs.ListByYear(ctx, year)
	if err != nil {
		t.Fatal(err)
	}
	if len(list2) != wantN {
		t.Fatalf("after second ensure: got %d holidays, want %d", len(list2), wantN)
	}
}

func TestEnsureNRWHolidays_skipsExistingDate(t *testing.T) {
	db, err := sqlite.Open(":memory:")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	ctx := context.Background()
	hs := sqlite.NewHolidayStore(db)
	year := 2026

	manual := &model.Holiday{HolidayDate: "2026-01-01", Name: "Manuell", AutoGenerated: false}
	if err := hs.Create(ctx, manual); err != nil {
		t.Fatal(err)
	}

	if err := EnsureNRWHolidays(ctx, hs, []int{year}); err != nil {
		t.Fatal(err)
	}

	got, err := hs.GetForDate(ctx, "2026-01-01")
	if err != nil {
		t.Fatal(err)
	}
	if got == nil {
		t.Fatal("expected row for 2026-01-01")
	}
	if got.Name != "Manuell" {
		t.Fatalf("manual name overwritten: got %q", got.Name)
	}

	wantN := len(timecalc.GenerateNRWHolidays(year))
	list, err := hs.ListByYear(ctx, year)
	if err != nil {
		t.Fatal(err)
	}
	if len(list) != wantN {
		t.Fatalf("total holidays: got %d want %d (manual + generated minus duplicate)", len(list), wantN)
	}
}

func TestCurrentAndNextCalendarYears(t *testing.T) {
	berlin, err := time.LoadLocation("Europe/Berlin")
	if err != nil {
		t.Skip("Europe/Berlin not available")
	}
	// 2026-01-01 00:30 in Berlin
	ts := time.Date(2026, 1, 1, 0, 30, 0, 0, berlin)
	years := CurrentAndNextCalendarYears(ts, berlin)
	if years[0] != 2026 || years[1] != 2027 {
		t.Fatalf("got %v want [2026 2027]", years)
	}
}

func TestHolidayCalendarLocation(t *testing.T) {
	loc, berlin := HolidayCalendarLocation()
	if loc == nil {
		t.Fatal("nil location")
	}
	// In normal environments Berlin loads; if not, UTC is acceptable.
	if berlin {
		if loc.String() != "Europe/Berlin" {
			t.Fatalf("unexpected loc: %s", loc.String())
		}
	}
}
