package handler

import (
	"context"
	"testing"
	"time"

	"nfc-time-tracking-server/internal/model"
)

type stubHolidayStore struct {
	getForDate func(ctx context.Context, date string) (*model.Holiday, error)
}

func (s stubHolidayStore) Create(context.Context, *model.Holiday) error { return nil }
func (s stubHolidayStore) Delete(context.Context, int) error             { return nil }
func (s stubHolidayStore) ListByYear(context.Context, int) ([]model.Holiday, error) {
	return nil, nil
}
func (s stubHolidayStore) GetForDate(ctx context.Context, date string) (*model.Holiday, error) {
	if s.getForDate != nil {
		return s.getForDate(ctx, date)
	}
	return nil, nil
}
func (s stubHolidayStore) DeleteAutoGenerated(context.Context, int) error { return nil }

type stubClosureStore struct {
	getForDate func(ctx context.Context, date string) (*model.ClosureDay, error)
}

func (stubClosureStore) Create(context.Context, *model.ClosureDay) error { return nil }
func (stubClosureStore) Delete(context.Context, int) error               { return nil }
func (stubClosureStore) List(context.Context) ([]model.ClosureDay, error) {
	return nil, nil
}

func (s stubClosureStore) GetForDate(ctx context.Context, date string) (*model.ClosureDay, error) {
	if s.getForDate != nil {
		return s.getForDate(ctx, date)
	}
	return nil, nil
}

func TestValidateVacationAbsenceDate(t *testing.T) {
	ctx := context.Background()
	st := stubHolidayStore{}

	t.Run("invalid date", func(t *testing.T) {
		if err := validateVacationAbsenceDate(ctx, st, nil, nil, "not-a-date"); err == nil {
			t.Fatal("expected error")
		}
	})

	t.Run("saturday", func(t *testing.T) {
		if err := validateVacationAbsenceDate(ctx, st, nil, nil, "2026-04-04"); err == nil {
			t.Fatal("expected error")
		}
	})

	t.Run("sunday", func(t *testing.T) {
		if err := validateVacationAbsenceDate(ctx, st, nil, nil, "2026-04-05"); err == nil {
			t.Fatal("expected error")
		}
	})

	t.Run("holiday", func(t *testing.T) {
		st := stubHolidayStore{
			getForDate: func(_ context.Context, date string) (*model.Holiday, error) {
				if date == "2026-04-06" {
					return &model.Holiday{HolidayDate: date, Name: "Ostermontag"}, nil
				}
				return nil, nil
			},
		}
		if err := validateVacationAbsenceDate(ctx, st, nil, nil, "2026-04-06"); err == nil {
			t.Fatal("expected error")
		}
	})

	t.Run("closure day", func(t *testing.T) {
		cs := stubClosureStore{
			getForDate: func(_ context.Context, date string) (*model.ClosureDay, error) {
				if date == "2026-04-08" {
					return &model.ClosureDay{ID: 1, ClosureDate: date, Name: "Betrieb"}, nil
				}
				return nil, nil
			},
		}
		if err := validateVacationAbsenceDate(ctx, st, cs, nil, "2026-04-08"); err == nil {
			t.Fatal("expected error on closure day")
		}
	})

	t.Run("weekday no holiday", func(t *testing.T) {
		if err := validateVacationAbsenceDate(ctx, st, nil, nil, "2026-04-07"); err != nil {
			t.Fatal(err)
		}
	})

	t.Run("fixed non-work weekday", func(t *testing.T) {
		fixed := []int{int(time.Tuesday)}
		if err := validateVacationAbsenceDate(ctx, st, nil, fixed, "2026-04-07"); err == nil {
			t.Fatal("expected error on fixed free Tuesday")
		}
	})
}
