package handler

import (
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"

	"nfc-time-tracking-server/internal/api/response"
	"nfc-time-tracking-server/internal/audit"
	"nfc-time-tracking-server/internal/model"
	"nfc-time-tracking-server/internal/service/timecalc"
	"nfc-time-tracking-server/internal/store"
)

// HolidayHandler verwaltet Feiertage (Lesen: Leitung/Superadmin; Schreiben: Superadmin).
type HolidayHandler struct {
	Holidays store.HolidayStore
	Audit    *audit.Logger
}

func (h *HolidayHandler) List(w http.ResponseWriter, r *http.Request) {
	yr, err := strconv.Atoi(r.URL.Query().Get("year"))
	if err != nil || yr < 1900 || yr > 3000 {
		response.Error(w, http.StatusBadRequest, "year required")
		return
	}
	list, err := h.Holidays.ListByYear(r.Context(), yr)
	if err != nil {
		response.Error(w, http.StatusInternalServerError, "query failed")
		return
	}
	response.JSON(w, http.StatusOK, map[string]interface{}{"holidays": list})
}

type holidayCreateBody struct {
	HolidayDate string `json:"holiday_date"`
	Name        string `json:"name"`
	Kind        string `json:"kind"`
}

func (h *HolidayHandler) Create(w http.ResponseWriter, r *http.Request) {
	var body holidayCreateBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		response.Error(w, http.StatusBadRequest, "invalid json")
		return
	}
	if body.HolidayDate == "" || body.Name == "" {
		response.Error(w, http.StatusBadRequest, "holiday_date and name required")
		return
	}
	kind := body.Kind
	if kind == "" {
		kind = model.HolidayKindFeiertag
	}
	if kind != model.HolidayKindFeiertag && kind != model.HolidayKindBrauchtum {
		response.Error(w, http.StatusBadRequest, "invalid kind")
		return
	}
	hol := &model.Holiday{HolidayDate: body.HolidayDate, Name: body.Name, Kind: kind, AutoGenerated: false}
	if err := h.Holidays.Create(r.Context(), hol); err != nil {
		response.Error(w, http.StatusBadRequest, err.Error())
		return
	}
	logAudit(h.Audit, r.Context(), audit.Entry{
		Action: audit.ActionCreate, EntityType: audit.EntityHoliday, EntityID: auditID(hol.ID),
		Summary: audit.JSONSummary(map[string]any{"holiday_date": hol.HolidayDate, "name": hol.Name}),
	})
	response.JSON(w, http.StatusCreated, hol)
}

func (h *HolidayHandler) Delete(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	if err != nil {
		response.Error(w, http.StatusBadRequest, "invalid id")
		return
	}
	if err := h.Holidays.Delete(r.Context(), id); err != nil {
		response.Error(w, http.StatusInternalServerError, "delete failed")
		return
	}
	logAudit(h.Audit, r.Context(), audit.Entry{
		Action: audit.ActionDelete, EntityType: audit.EntityHoliday, EntityID: auditID(id),
	})
	w.WriteHeader(http.StatusNoContent)
}

func (h *HolidayHandler) Generate(w http.ResponseWriter, r *http.Request) {
	yr, err := strconv.Atoi(r.URL.Query().Get("year"))
	if err != nil {
		response.Error(w, http.StatusBadRequest, "year required")
		return
	}
	if err := h.Holidays.DeleteAutoGenerated(r.Context(), yr); err != nil {
		response.Error(w, http.StatusInternalServerError, "delete auto failed")
		return
	}
	for _, hh := range timecalc.GenerateNRWHolidays(yr) {
		x := hh
		if err := h.Holidays.Create(r.Context(), &x); err != nil {
			response.Error(w, http.StatusInternalServerError, "insert failed")
			return
		}
	}
	logAudit(h.Audit, r.Context(), audit.Entry{
		Action: audit.ActionUpdate, EntityType: audit.EntityHoliday, EntityID: "generate",
		Summary: audit.JSONSummary(map[string]any{"year": yr}),
	})
	response.JSON(w, http.StatusOK, map[string]string{"status": "ok"})
}
