package timecalc

import (
	"testing"

	"nfc-time-tracking-server/internal/model"
)

func TestEasterDate(t *testing.T) {
	tests := []struct {
		year  int
		month int
		day   int
	}{
		{2024, 3, 31},
		{2025, 4, 20},
		{2026, 4, 5},
		{2027, 3, 28},
	}
	for _, tt := range tests {
		m, d := easterDate(tt.year)
		if m != tt.month || d != tt.day {
			t.Errorf("Easter %d: expected %d-%02d, got %d-%02d", tt.year, tt.month, tt.day, m, d)
		}
	}
}

func TestRosenmontag(t *testing.T) {
	tests := map[int]string{
		2024: "2024-02-12",
		2026: "2026-02-16",
		2027: "2027-02-08",
	}
	for year, want := range tests {
		holidays := GenerateNRWHolidays(year)
		var got string
		for _, h := range holidays {
			if h.Name == "Rosenmontag" {
				got = h.HolidayDate
				break
			}
		}
		if got != want {
			t.Errorf("Rosenmontag %d: got %s want %s", year, got, want)
		}
	}
}

func TestGenerateNRWHolidays(t *testing.T) {
	holidays := GenerateNRWHolidays(2026)
	if len(holidays) != 14 {
		t.Fatalf("expected 14 holidays, got %d", len(holidays))
	}

	expected := map[string]struct {
		name string
		kind string
	}{
		"2026-01-01": {name: "Neujahr", kind: model.HolidayKindFeiertag},
		"2026-02-16": {name: "Rosenmontag", kind: model.HolidayKindBrauchtum},
		"2026-04-03": {name: "Karfreitag", kind: model.HolidayKindFeiertag},
		"2026-04-06": {name: "Ostermontag", kind: model.HolidayKindFeiertag},
		"2026-05-01": {name: "Tag der Arbeit", kind: model.HolidayKindFeiertag},
		"2026-05-14": {name: "Christi Himmelfahrt", kind: model.HolidayKindFeiertag},
		"2026-05-25": {name: "Pfingstmontag", kind: model.HolidayKindFeiertag},
		"2026-06-04": {name: "Fronleichnam", kind: model.HolidayKindFeiertag},
		"2026-10-03": {name: "Tag der Deutschen Einheit", kind: model.HolidayKindFeiertag},
		"2026-11-01": {name: "Allerheiligen", kind: model.HolidayKindFeiertag},
		"2026-12-24": {name: "Heiligabend", kind: model.HolidayKindBrauchtum},
		"2026-12-25": {name: "1. Weihnachtstag", kind: model.HolidayKindFeiertag},
		"2026-12-26": {name: "2. Weihnachtstag", kind: model.HolidayKindFeiertag},
		"2026-12-31": {name: "Silvester", kind: model.HolidayKindBrauchtum},
	}

	for _, h := range holidays {
		exp, ok := expected[h.HolidayDate]
		if !ok {
			t.Errorf("unexpected holiday: %s %s", h.HolidayDate, h.Name)
			continue
		}
		if h.Name != exp.name {
			t.Errorf("for %s: expected name %q, got %q", h.HolidayDate, exp.name, h.Name)
		}
		if h.Kind != exp.kind {
			t.Errorf("for %s: expected kind %q, got %q", h.HolidayDate, exp.kind, h.Kind)
		}
		if !h.AutoGenerated {
			t.Errorf("expected auto_generated=true for %s", h.HolidayDate)
		}
	}
}
