package timecalc

import "testing"

func TestEasterDate(t *testing.T) {
	tests := []struct {
		year  int
		month int
		day   int
	}{
		{2024, 3, 31},
		{2025, 4, 20},
		{2026, 4, 5},
		{2027, 3, 28},
	}
	for _, tt := range tests {
		m, d := easterDate(tt.year)
		if m != tt.month || d != tt.day {
			t.Errorf("Easter %d: expected %d-%02d, got %d-%02d", tt.year, tt.month, tt.day, m, d)
		}
	}
}

func TestGenerateNRWHolidays(t *testing.T) {
	holidays := GenerateNRWHolidays(2026)
	if len(holidays) != 11 {
		t.Fatalf("expected 11 NRW holidays, got %d", len(holidays))
	}

	expected := map[string]string{
		"2026-01-01": "Neujahr",
		"2026-04-03": "Karfreitag",
		"2026-04-06": "Ostermontag",
		"2026-05-01": "Tag der Arbeit",
		"2026-05-14": "Christi Himmelfahrt",
		"2026-05-25": "Pfingstmontag",
		"2026-06-04": "Fronleichnam",
		"2026-10-03": "Tag der Deutschen Einheit",
		"2026-11-01": "Allerheiligen",
		"2026-12-25": "1. Weihnachtstag",
		"2026-12-26": "2. Weihnachtstag",
	}

	for _, h := range holidays {
		exp, ok := expected[h.HolidayDate]
		if !ok {
			t.Errorf("unexpected holiday: %s %s", h.HolidayDate, h.Name)
			continue
		}
		if h.Name != exp {
			t.Errorf("for %s: expected %q, got %q", h.HolidayDate, exp, h.Name)
		}
		if !h.AutoGenerated {
			t.Errorf("expected auto_generated=true for %s", h.HolidayDate)
		}
	}
}
