package timecalc

import (
	"fmt"
	"time"

	"nfc-time-tracking-server/internal/model"
)

// easterDate returns month and day of Easter Sunday (Western) for year.
func easterDate(year int) (month, day int) {
	a := year % 19
	b := year / 100
	c := year % 100
	d := b / 4
	e := b % 4
	f := (b + 8) / 25
	g := (b - f + 1) / 3
	h := (19*a + b - d - g + 15) % 30
	i := c / 4
	k := c % 4
	l := (32 + 2*e + 2*i - h - k) % 7
	m := (a + 11*h + 22*l) / 451
	month = (h + l - 7*m + 114) / 31
	day = ((h + l - 7*m + 114) % 31) + 1
	return month, day
}

func easterTime(year int) time.Time {
	m, d := easterDate(year)
	return time.Date(year, time.Month(m), d, 0, 0, 0, 0, time.UTC)
}

// GenerateNRWHolidays returns fixed and movable NRW public holidays for year.
func GenerateNRWHolidays(year int) []model.Holiday {
	e := easterTime(year)
	add := func(t time.Time, name string) model.Holiday {
		return model.Holiday{
			HolidayDate:   t.Format("2006-01-02"),
			Name:          name,
			AutoGenerated: true,
		}
	}
	out := []model.Holiday{
		add(time.Date(year, 1, 1, 0, 0, 0, 0, time.UTC), "Neujahr"),
		add(e.AddDate(0, 0, -2), "Karfreitag"),
		add(e.AddDate(0, 0, 1), "Ostermontag"),
		add(time.Date(year, 5, 1, 0, 0, 0, 0, time.UTC), "Tag der Arbeit"),
		add(e.AddDate(0, 0, 39), "Christi Himmelfahrt"),
		add(e.AddDate(0, 0, 50), "Pfingstmontag"),
		add(e.AddDate(0, 0, 60), "Fronleichnam"),
		add(time.Date(year, 10, 3, 0, 0, 0, 0, time.UTC), "Tag der Deutschen Einheit"),
		add(time.Date(year, 11, 1, 0, 0, 0, 0, time.UTC), "Allerheiligen"),
		add(time.Date(year, 12, 25, 0, 0, 0, 0, time.UTC), "1. Weihnachtstag"),
		add(time.Date(year, 12, 26, 0, 0, 0, 0, time.UTC), "2. Weihnachtstag"),
	}
	return out
}

// ValidateEasterAgainstReference checks a few known Easter Sundays.
func ValidateEasterAgainstReference(year, wantMonth, wantDay int) error {
	m, d := easterDate(year)
	if m != wantMonth || d != wantDay {
		return fmt.Errorf("year %d: easter got %d-%02d, want %d-%02d", year, m, d, wantMonth, wantDay)
	}
	return nil
}
