package saldocalc

import (
	"context"
	"testing"
	"time"

	"nfc-time-tracking-server/internal/model"
)

type stubFNWStore struct{}

func (s stubFNWStore) Set(ctx context.Context, row *model.FixedNonWorkWeekdays) error { return nil }
func (s stubFNWStore) Delete(ctx context.Context, userID int, id int) error            { return nil }
func (s stubFNWStore) GetByID(ctx context.Context, userID int, id int) (*model.FixedNonWorkWeekdays, error) {
	return nil, nil
}
func (s stubFNWStore) GetForDate(ctx context.Context, userID int, date string) (*model.FixedNonWorkWeekdays, error) {
	return &model.FixedNonWorkWeekdays{UserID: userID, ValidFrom: "2000-01-01", Weekdays: nil}, nil
}
func (s stubFNWStore) ListByUser(ctx context.Context, userID int) ([]model.FixedNonWorkWeekdays, error) {
	return []model.FixedNonWorkWeekdays{{UserID: userID, ValidFrom: "2000-01-01", Weekdays: nil}}, nil
}

type stubWorkPeriodStore struct{}

func (s stubWorkPeriodStore) ReplaceForUserDate(ctx context.Context, userID int, date string, periods []model.WorkPeriod) error {
	return nil
}
func (s stubWorkPeriodStore) ListByUserDateRange(ctx context.Context, userID int, from, to string) ([]model.WorkPeriod, error) {
	return []model.WorkPeriod{}, nil
}
func (s stubWorkPeriodStore) GetByID(ctx context.Context, id int) (*model.WorkPeriod, error) { return nil, nil }
func (s stubWorkPeriodStore) CreateManual(ctx context.Context, wp *model.WorkPeriod) error    { return nil }
func (s stubWorkPeriodStore) DeleteManual(ctx context.Context, id int) error                   { return nil }

type stubWeeklyHoursStore struct {
	validFrom string
	hours     float64
}

func (s stubWeeklyHoursStore) Set(ctx context.Context, wh *model.WeeklyHours) error    { return nil }
func (s stubWeeklyHoursStore) Delete(ctx context.Context, userID int, id int) error     { return nil }
func (s stubWeeklyHoursStore) GetByID(ctx context.Context, userID int, id int) (*model.WeeklyHours, error) {
	return nil, nil
}
func (s stubWeeklyHoursStore) GetForDate(ctx context.Context, userID int, date string) (*model.WeeklyHours, error) {
	if date < s.validFrom {
		return nil, nil
	}
	return &model.WeeklyHours{UserID: userID, HoursPerWeek: s.hours, ValidFrom: s.validFrom}, nil
}
func (s stubWeeklyHoursStore) ListByUser(ctx context.Context, userID int) ([]model.WeeklyHours, error) {
	return []model.WeeklyHours{}, nil
}

type stubHolidayStore struct {
	holidays map[string]bool
}

func (s stubHolidayStore) Create(ctx context.Context, h *model.Holiday) error { return nil }
func (s stubHolidayStore) Delete(ctx context.Context, id int) error            { return nil }
func (s stubHolidayStore) ListByYear(ctx context.Context, year int) ([]model.Holiday, error) {
	return []model.Holiday{}, nil
}
func (s stubHolidayStore) GetForDate(ctx context.Context, date string) (*model.Holiday, error) {
	if s.holidays != nil && s.holidays[date] {
		return &model.Holiday{ID: 1, HolidayDate: date, Name: "Holiday"}, nil
	}
	return nil, nil
}
func (s stubHolidayStore) DeleteAutoGenerated(ctx context.Context, year int) error { return nil }

type stubAbsenceStore struct {
	byRange []model.Absence
}

func (s stubAbsenceStore) Create(ctx context.Context, a *model.Absence) error { return nil }
func (s stubAbsenceStore) Delete(ctx context.Context, id int) error           { return nil }
func (s stubAbsenceStore) GetByID(ctx context.Context, id int) (*model.Absence, error) {
	return nil, nil
}
func (s stubAbsenceStore) ListByDateRangeTypes(ctx context.Context, from, to string, types []model.AbsenceType) ([]model.Absence, error) {
	return nil, nil
}
func (s stubAbsenceStore) GetForUserDate(ctx context.Context, userID int, date string) (*model.Absence, error) {
	for i := range s.byRange {
		a := &s.byRange[i]
		ds := a.AbsenceDate
		if len(ds) >= 10 {
			ds = ds[:10]
		}
		if ds == date {
			return a, nil
		}
	}
	return nil, nil
}
func (s stubAbsenceStore) ListByUserDateRange(ctx context.Context, userID int, from, to string) ([]model.Absence, error) {
	var out []model.Absence
	for _, a := range s.byRange {
		ds := a.AbsenceDate
		if len(ds) >= 10 {
			ds = ds[:10]
		}
		if ds >= from && ds <= to {
			out = append(out, a)
		}
	}
	return out, nil
}

func TestMonthWithOpening_UsesPartialMonthWeeklyHours(t *testing.T) {
	ctx := context.Background()
	mb, err := MonthWithOpening(
		ctx,
		1,
		2026,
		5,
		0,
		stubFNWStore{},
		stubWorkPeriodStore{},
		stubWeeklyHoursStore{validFrom: "2026-05-25", hours: 40},
		stubHolidayStore{},
		stubAbsenceStore{},
		nil,
		nil,
	)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	loc := time.Local
	var wantTarget float64
	for d := time.Date(2026, time.May, 25, 0, 0, 0, 0, loc); d.Month() == time.May; d = d.AddDate(0, 0, 1) {
		if d.Weekday() != time.Saturday && d.Weekday() != time.Sunday {
			wantTarget += 8
		}
	}
	if mb.TargetHours != wantTarget {
		t.Fatalf("target got %v want %v", mb.TargetHours, wantTarget)
	}
	if mb.BalanceHours != -wantTarget {
		t.Fatalf("balance got %v want %v", mb.BalanceHours, -wantTarget)
	}
	if mb.TotalBalance != -wantTarget {
		t.Fatalf("total got %v want %v", mb.TotalBalance, -wantTarget)
	}
	if mb.Carryover != 0 {
		t.Fatalf("carryover got %v want 0", mb.Carryover)
	}
}

func TestMonthWithOpening_IncludesHolidayCreditInWorked(t *testing.T) {
	ctx := context.Background()
	mb, err := MonthWithOpening(
		ctx,
		1,
		2026,
		5,
		0,
		stubFNWStore{},
		stubWorkPeriodStore{},
		stubWeeklyHoursStore{validFrom: "2026-05-01", hours: 40},
		stubHolidayStore{holidays: map[string]bool{"2026-05-25": true}},
		stubAbsenceStore{},
		nil,
		nil,
	)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if mb.WorkedHours != 8 {
		t.Fatalf("worked got %v want 8", mb.WorkedHours)
	}
}

func TestMonthWithOpening_IncludesVacationCreditAtDailyTarget(t *testing.T) {
	ctx := context.Background()
	wh := stubWeeklyHoursStore{validFrom: "2026-03-01", hours: 30}
	mbNoVac, err := MonthWithOpening(
		ctx, 1, 2026, 3, 0,
		stubFNWStore{}, stubWorkPeriodStore{}, wh, stubHolidayStore{}, stubAbsenceStore{}, nil, nil,
	)
	if err != nil {
		t.Fatalf("baseline: %v", err)
	}
	mbVac, err := MonthWithOpening(
		ctx, 1, 2026, 3, 0,
		stubFNWStore{}, stubWorkPeriodStore{}, wh, stubHolidayStore{},
		stubAbsenceStore{byRange: []model.Absence{{
			UserID: 1, AbsenceDate: "2026-03-10", AbsenceType: model.AbsenceVacation,
		}}},
		nil, nil,
	)
	if err != nil {
		t.Fatalf("vacation: %v", err)
	}
	if mbVac.WorkedHours != 6 {
		t.Fatalf("worked got %v want 6", mbVac.WorkedHours)
	}
	if mbVac.TargetHours != mbNoVac.TargetHours {
		t.Fatalf("target changed: %v vs %v", mbVac.TargetHours, mbNoVac.TargetHours)
	}
	if mbVac.BalanceHours-mbNoVac.BalanceHours != 6 {
		t.Fatalf("balance delta got %v want 6", mbVac.BalanceHours-mbNoVac.BalanceHours)
	}
}

func TestMonthWithOpening_VacationWithoutWeeklyHoursZeroCredit(t *testing.T) {
	ctx := context.Background()
	mbNoVac, err := MonthWithOpening(
		ctx, 1, 2026, 3, 0,
		stubFNWStore{},
		stubWorkPeriodStore{},
		stubWeeklyHoursStore{validFrom: "2099-01-01", hours: 40},
		stubHolidayStore{},
		stubAbsenceStore{},
		nil, nil,
	)
	if err != nil {
		t.Fatalf("baseline: %v", err)
	}
	mbVac, err := MonthWithOpening(
		ctx, 1, 2026, 3, 0,
		stubFNWStore{},
		stubWorkPeriodStore{},
		stubWeeklyHoursStore{validFrom: "2099-01-01", hours: 40},
		stubHolidayStore{},
		stubAbsenceStore{byRange: []model.Absence{{
			UserID: 1, AbsenceDate: "2026-03-10", AbsenceType: model.AbsenceVacation,
		}}},
		nil, nil,
	)
	if err != nil {
		t.Fatalf("vacation: %v", err)
	}
	if mbVac.WorkedHours != 0 {
		t.Fatalf("worked got %v want 0", mbVac.WorkedHours)
	}
	if mbVac.TargetHours != mbNoVac.TargetHours {
		t.Fatalf("target with vacation %v want %v", mbVac.TargetHours, mbNoVac.TargetHours)
	}
	if mbVac.BalanceHours != 0 {
		t.Fatalf("balance got %v want 0", mbVac.BalanceHours)
	}
}
