package sqlite

import (
	"context"
	"database/sql"
	"fmt"
	"strconv"

	"nfc-time-tracking-server/internal/model"
)

type HolidayStore struct {
	db *DB
}

func NewHolidayStore(db *DB) *HolidayStore {
	return &HolidayStore{db: db}
}

func (s *HolidayStore) Create(ctx context.Context, h *model.Holiday) error {
	res, err := s.db.DB.ExecContext(ctx,
		`INSERT INTO holidays (holiday_date, name, auto_generated) VALUES (?, ?, ?)`,
		h.HolidayDate, h.Name, h.AutoGenerated)
	if err != nil {
		return fmt.Errorf("create holiday: %w", err)
	}
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}
	h.ID = int(id)
	return nil
}

func (s *HolidayStore) Delete(ctx context.Context, id int) error {
	_, err := s.db.DB.ExecContext(ctx, `DELETE FROM holidays WHERE id = ?`, id)
	return err
}

func (s *HolidayStore) ListByYear(ctx context.Context, year int) ([]model.Holiday, error) {
	prefix := strconv.Itoa(year) + "-"
	rows, err := s.db.DB.QueryContext(ctx,
		`SELECT id, holiday_date, name, auto_generated FROM holidays WHERE holiday_date LIKE ? ORDER BY holiday_date`,
		prefix+"%")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var list []model.Holiday
	for rows.Next() {
		var h model.Holiday
		if err := rows.Scan(&h.ID, &h.HolidayDate, &h.Name, &h.AutoGenerated); err != nil {
			return nil, err
		}
		list = append(list, h)
	}
	return list, rows.Err()
}

func (s *HolidayStore) GetForDate(ctx context.Context, date string) (*model.Holiday, error) {
	h := &model.Holiday{}
	err := s.db.DB.QueryRowContext(ctx,
		`SELECT id, holiday_date, name, auto_generated FROM holidays WHERE holiday_date = ?`, date).
		Scan(&h.ID, &h.HolidayDate, &h.Name, &h.AutoGenerated)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return h, nil
}

func (s *HolidayStore) DeleteAutoGenerated(ctx context.Context, year int) error {
	prefix := strconv.Itoa(year) + "-"
	_, err := s.db.DB.ExecContext(ctx,
		`DELETE FROM holidays WHERE auto_generated = 1 AND holiday_date LIKE ?`, prefix+"%")
	return err
}
